### ISSUE TITLE
Change UseCases Names

### ISSUE THREAD

**Issue by eduardoGandorphi** [tamiriamfernandes/mysales#1]
### UseCases
- [x] Use Cases names should represent events, not entities 
- [x] Each Use Case should have only one public method, which is the main event 
- [x] This public method should call its own private methods or Core methods 
- [x] Use Case's private methods should be only an aggregation of core’s calls 
- [x] A Use Case can not call another Use Case

**Comment by tamiriamfernandes** [comment]
Use Cases names should represent events, not entities: exemplo criar um crud use case de clientes para ter os comandos básicos;
